# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(choices=[('request.xml', 'request.xml'), ('request.xml.sign', 'request.xml.sign')], max_length=64, unique=True, verbose_name='Имя файла')),
                ('data', models.FileField(upload_to='auth_files', verbose_name='Файл')),
            ],
            options={
                'db_table': 'auth_files',
                'managed': True,
            },
        ),
    ]
