# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoskomAPIRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Код')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'db_table': 'api_requests',
                'managed': True,
            },
        ),
    ]
