# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_roskomapirequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Имя параметра')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Значение')),
            ],
            options={
                'managed': True,
                'db_table': 'settings',
            },
        ),
        migrations.DeleteModel(
            name='RoskomAPIRequest',
        ),
    ]
