# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20160310_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Код')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('state', models.CharField(choices=[('new', 'Обрабатывается'), ('sent-request', 'Запрос отправлен'), ('got-response', 'Выполнена'), ('failed', 'Произошла ошибка')], default='new', max_length=15, verbose_name='Статус')),
                ('mode', models.CharField(choices=[('automatic', 'Автоматическая'), ('manual', 'Ручная')], default='automatic', max_length=15, verbose_name='Тип')),
            ],
            options={
                'managed': True,
                'db_table': 'downloads',
            },
        ),
    ]
