# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='state',
            field=models.CharField(choices=[('new', 'Запрос отправлен'), ('got-response', 'Выполнена'), ('failed', 'Произошла ошибка')], default='new', max_length=15, verbose_name='Статус'),
        ),
    ]
