# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_download_debug'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='error',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ошибка'),
        ),
    ]
