# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_download_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='URL')),
            ],
            options={
                'managed': True,
                'db_table': 'available_links',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('state', models.CharField(choices=[('started', 'Начата'), ('working', 'Выполняется'), ('finished', 'Завершена')], default='started', max_length=15, verbose_name='Статус')),
                ('mode', models.CharField(choices=[('automatic', 'Автоматическая'), ('manual', 'Ручная')], default='automatic', max_length=15, verbose_name='Тип')),
                ('total', models.IntegerField(default=0, verbose_name='Всего URL')),
                ('unavailable', models.IntegerField(default=0, verbose_name='Недоступных URL')),
                ('available', models.IntegerField(default=0, verbose_name='Доступных URL')),
                ('local', models.IntegerField(default=0, verbose_name='URL с локальными IP')),
            ],
            options={
                'managed': True,
                'db_table': 'scans',
            },
        ),
        migrations.AddField(
            model_name='availablelink',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Scan', verbose_name='Проверка'),
        ),
    ]
