# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20160311_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'managed': True, 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='scan',
            options={'managed': True, 'ordering': ('-started',)},
        ),
        migrations.AddField(
            model_name='download',
            name='duration',
            field=models.FloatField(default=0.0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='download',
            name='filesize',
            field=models.IntegerField(default=0, verbose_name='Объём'),
        ),
    ]
