# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20160314_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='task_pid',
            field=models.IntegerField(default=0, verbose_name='PID'),
        ),
    ]
