# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_download_task_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='state',
            field=models.CharField(choices=[('new', 'Выполняется'), ('got-response', 'Выполнена'), ('failed', 'Ошибка')], default='new', max_length=15, verbose_name='Статус'),
        ),
    ]
