# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20160314_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=16, verbose_name='Уровень')),
                ('module', models.CharField(choices=[('web', 'Веб-интерфейс'), ('roskom_load', 'roskom_load'), ('roskom_check', 'roskom_check')], default='web', max_length=16, verbose_name='Команда')),
                ('message', models.CharField(default='', max_length=1024, verbose_name='Сообщение')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'db_table': 'log',
                'managed': True,
            },
        ),
    ]
