# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 07:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Прогресс'),
        ),
    ]
