# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_scan_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='finished',
        ),
        migrations.AlterField(
            model_name='scan',
            name='state',
            field=models.CharField(choices=[('started', 'Начата'), ('failed', 'Ошибка'), ('finished', 'Завершена')], default='started', max_length=15, verbose_name='Статус'),
        ),
    ]
