# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20160315_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='task_pid',
            field=models.IntegerField(default=0, verbose_name='PID'),
        ),
    ]
