# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_scan_task_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершена'),
        ),
    ]
