# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_scan_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='error',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ошибка'),
        ),
    ]
