# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_scan_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='mode',
            field=models.CharField(choices=[('automatic', 'Автоматическая'), ('manual', 'Ручная'), ('web', 'Веб')], default='automatic', max_length=15, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='mode',
            field=models.CharField(choices=[('automatic', 'Автоматическая'), ('manual', 'Ручная'), ('web', 'Веб')], default='automatic', max_length=15, verbose_name='Тип'),
        ),
    ]
