# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('portal', '0021_auto_20160324_0951'),
	]

	def create_user(apps, schema_editor):
		#User = apps.get_model("django.contrib.auth", "User")
		from django.contrib.auth.models import User
		admin = User(username = 'admin', password = '', is_staff = True, is_active = True, is_superuser = True)
		admin.set_password('123456')
		admin.save()

	operations = [
		migrations.RunPython(create_user),
	]
